<?php
// This script was generated by an AI assistant (Claude 3.5 Sonnet)

// Get the current date and time
$current_datetime = date('Y-m-d H:i:s');

// Generate a random number
$random_number = rand(1, 100);

// Output the information
echo "<h1>Welcome to my test website!</h1>";
echo "<p>This page was generated by a PHP script written by an AI assistant.</p>";
echo "<p>Current date and time: " . $current_datetime . "</p>";
echo "<p>Here's a random number between 1 and 100: " . $random_number . "</p>";
echo "<p>Refresh the page to see the values change!</p>";
?>


// phpMyAdmin Version: <?php echo getenv('PHPMYADMIN_VERSION'); ?> 
